FORMAT: 1A
HOST: http://www.google.com

# GameSayer
GAmeSayer API is a game consumption service similar to youtube, but for the consumption of games instead of videos.

# Group Users
User related resources of the **GameSayer API**

## Users Collection [/users]
### List all Users [GET]
+ Response 200 (application/json)

        [{ "id": "ae1234cc", "name": "Sherlock Holmes", "email":'sherlock@gmail.com', "description":"Loves Smoking. Hates Scotland Yard." ,
        "credits":0,"subscribers":0,"channelLimit":100}
        ,  "id": "ae1234bb", "name": "Watson", "email":'watson@gmail.com', "description":"War Veteran. Doctor." ,
        "credits":0,"subscribers":0,"channelLimit":100}]

### Create a User [POST]
+ Request (application/json)

        { "name": "Sherlock Holmes" ,"email":"sherlock@gmail.com", description:"Loves Smoking. Hates Scotland Yard." }

+ Response 201 (application/json)

        { "id": "ae1234cc", "name": "Sherlock Holmes", "email":'sherlock@gmail.com', "description":"Loves Smoking. Hates Scotland Yard." ,"credits":0,"subscribers":0,"channelLimit":100}
            

## User [/users/{userid}]
A single User object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a User [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": "ae1234cc", "name": "Sherlock Holmes", "email":'sherlock@gmail.com', "description":"Loves Smoking. Hates Scotland Yard.", "credits":0,"subscribers":0,"channelLimit":100}
            

#Group Games

##Games
## Games Collection [/games]
These are the games that are available on GameSayer. These games are just an abstract entity. They cant be player.
In order to play them, these Games must be created by Users. An example is that QuizSpin is a Game, however it can only be played once a user
puts content and customizes it according to his need.

### List all Games [GET]
+ Response 200 (application/json)

        [{ "id": "ae1234cc", "name": "Sherlock Holmes", "email":'sherlock@gmail.com', "description":"Loves Smoking. Hates Scotland Yard." ,
        "credits":0,"subscribers":0,"channelLimit":100}
        ,  "id": "ae1234bb", "name": "Watson", "email":'watson@gmail.com', "description":"War Veteran. Doctor." ,
        "credits":0,"subscribers":0,"channelLimit":100}]


            