FORMAT: 1A
HOST: http://www.google.com

# GameSayer
GAmeSayer API is a game consumption service similar to youtube, but for the consumption of games instead of videos.

# Group Users
User related resources of the **GameSayer API**

## Users Collection [/users]
### List all Users [GET]
+ Response 200 (application/json)

        [{ "_id": "ae1234cc", "name": "Sherlock Holmes", "email":'sherlock@gmail.com', "description":"Loves Smoking. Hates Scotland Yard." ,
        "credits":0,"subscribers":0,"channelLimit":100}
        ,  "_id": "ae1234bb", "name": "Watson", "email":'watson@gmail.com', "description":"War Veteran. Doctor." ,
        "credits":0,"subscribers":0,"channelLimit":100}]

### Create a User [POST]
+ Request (application/json)

        { "name": "Sherlock Holmes" ,"email":"sherlock@gmail.com", description:"Loves Smoking. Hates Scotland Yard." }

+ Response 201 (application/json)

        { "_id": "ae1234cc", "name": "Sherlock Holmes", "email":'sherlock@gmail.com', "description":"Loves Smoking. Hates Scotland Yard." ,"credits":0,"subscribers":0,"channelLimit":100}
            

## User [/users/{userId}]
A single User object with all its details

+ Parameters
    + userId (required, string, `ae1234cc`) ... String `id` of the Note to perform action with. Has example value.

### Retrieve a User [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { 
                "_id": "ae1234cc", 
                "name": "Sherlock Holmes", 
                "email":'sherlock@gmail.com', 
                "description":"Loves Smoking. Hates Scotland Yard.", 
                "credits":0,
                "subscribers":0,
                "channelLimit":100
            }
            

#Group Games

##Games
## Games Collection [/games]
These are the games that are available on GameSayer. These games are just an abstract entity. They cant be player.
In order to play them, these Games must be created by Users. An example is that QuizSpin is a Game, however it can only be played once a user
puts content and customizes it according to his need.

### List all Games [GET]
+ Response 200 (application/json)

        [
        { 
            "_id": "eb1234a1", "name": "QuizSpin", "description":"Chance based quiz game. Kind of like a slots machine" ,
        }
        ,{
            "_id": "eb1234b1", "name": "Grail Hunter", "description":"Find the Grail. Answer the questions. Be awesome." 
        }]
        
## User Games Collection [/users/{userId}/games/created]
User Games are the games a user creates from a set of game types. These games are not games in the traditional sense of the term.
These games represent some content. This content is in the form of questions and slides. When a user playes this "game", he is 
essentially choosing to play said content. The manner in which he plays it (grail hunter/quizspin) is irrelevant.

### List a particular User's Games [GET]
+ Response 200 (application/json)

    + Body
    
            [{
                "name": "QuizSpin",
                "_id":"ac1234ff",
                "description":"Content on Martin Scorcese's famous movies",
                "selectors":[],
                "topics":["movies","entertainment"],
                "likes":25,
                "dislikes":2,
                "shares":24,
                "categories":["entertainment"],
                "views":50,
                "rewards":["house","tv"],
                "tags":["indie","de niro","the departed"],
                "userdata”:[
                    {"user_id":1, "days_played":3, "km_clicks":9, "srt_score":17, "fin_score":45},
                    {"user_id":2, "days_played":5, "km_clicks":6, "srt_score":14, "fin_score":58},
                    {"user_id":3, "days_played":5, "km_clicks":10, "srt_score":26, "fin_score":77},
                    {"user_id":4, "days_played":4, "km_clicks":8, "srt_score":27, "fin_score":62},
                    {"user_id":5, "days_played":4, "km_clicks":10, "srt_score":43, "fin_score":97},
                    {"user_id":6, "days_played":4, "km_clicks":5, "srt_score":20, "fin_score":58},
                    {"user_id":7, "days_played":4, "km_clicks":5, "srt_score":9, "fin_score":85},
                    {"user_id":8, "days_played":1, "km_clicks":10, "srt_score":24, "fin_score":85},
                    {"user_id":9, "days_played":5, "km_clicks":7, "srt_score":41, "fin_score":79},
                    {"user_id":10, "days_played":5, "km_clicks":9, "srt_score":17, "fin_score":66}
                ]
            }]
            
### Create a particular User Game [POST]
+ Response 200 (application/json)

    + Body
    
            {
                "name": "QuizSpin",
                "_id":"ac1234ff",
                "description":"Content on Stanley Kubrick's famous movies",
                "selectors":[],
                "topics":["movies","entertainment"],
                "categories":["entertainment"],
                "rewards":["house","tv"],
                "tags":["indie","space odessey"],
            }


#Group Topics
## Topics Collection [/topics]

### List topics [GET]
+ Response 200 (application/json)

    + Body
        
            [{
                "name":"movies"
                "games":[{
                    "name": "QuizSpin",
                    "_id":"ac1234ff",
                    "description":"Content on Stanley Kubrick's famous movies",
                    "author":{}
                    "categories":["entertainment"]
                }]
            }]

## Trending Topics Collection [/trendingtopics]
+ Response 200 (application/json)

    + Body
        
            [{
                "name":"indipop"
                "games":[{
                    "name": "QuizSpin",
                    "_id":"ac1234ac",
                    "description":"Content on Bollywood's most famous pop songs",
                    "author":
                    { 
                        "_id": "ae1234cc", 
                        "name": "Sherlock Holmes", 
                        "email":'sherlock@gmail.com', 
                        "description":"Loves Smoking. Hates Scotland Yard.", 
                        "credits":0,
                        "subscribers":0,
                        "channelLimit":100
                    }
                    "categories":["entertainment"]
                }]
            },{
                "name":"yoyo honey singh"
                "games":[{
                    "name": "QuizSpin",
                    "_id":"ab1234bc",
                    "description":"Content on Bollywood's shittiest songs",
                    "author":
                    { 
                        "_id": "ae1234cc", 
                        "name": "Sherlock Holmes", 
                        "email":'sherlock@gmail.com', 
                        "description":"Loves Smoking. Hates Scotland Yard.", 
                        "credits":0,
                        "subscribers":0,
                        "channelLimit":100
                    }
                    "categories":["entertainment"]
                }]
            }]
